### ISSUE TITLE
jpg with odd dimensions fails to convert to `.nutexb` with no error message

### ISSUE THREAD

**Issue by AlexAzumi** [ScanMountGoat/ultimate_tex#14]
I tried to convert a `.png` image and the only result I get is "Converted 0 of 1 images". No matter the format I try to convert to, the same thing happens, except `.png` to `.png`.
I though that it was an error generated by the odd size of the image, but I changed the size to be square (500px by 500px) and the same thing occurs.
Could it be a weird property of the image?

**Comment by ScanMountGoat** [comment]
Can you take a screenshot of the settings you're using? This may be related to #13.

**Comment by AlexAzumi** [comment]
These are the settings that I'm using

![image](https://github.com/ScanMountGoat/ultimate_tex/assets/20672555/0139c7a1-ab0e-43d9-ab5d-890bc194cc79)

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this on my end. The width and height should be divisible by 4, so the texture needs to be resized or use an uncompressed format like R8G8B8A8Unorm. While odd dimensions are technically allowed by some formats like DDS, it still ends up taking up the additional size due to padding. It can also cause compatibility issues on desktop. I'll try and improve the error messages for the next release. If you need odd texture dimensions with BCN compression for a specific use case, please open a new issue and I'll consider it for a future release.
