### ISSUE TITLE
Options to set compression level for all images

### ISSUE THREAD

**Issue by Arlisbloxer05** [ScanMountGoat/ultimate_tex#4]
Not an issue, more an enhancement idea. Being able to set compression levels for all images at once would be really nice. It is a bit tedious to have to set them all one by one, which is honestly a bit surprising that it's not already in given how there's options to set everything as PNGs, BNTXs, etc.

Would love to see this change be in the program!

**Comment by ScanMountGoat** [comment]
What images are you trying to convert? What settings are you wanting to set like BC7 vs BC3 or Fast vs Slow? This would be simple to implement, but I would like to better understand the use case first before I make any changes.

**Comment by DevorySSBU** [comment]
I believe he means for fast, slow, normal.

I actually do want this too. It's automatically set to 'fast', but I believe a drop-down or option or even config to memorize the selection there would be great.

The use case would be if you wanted, for example, to convert UI files, and you're going about 6 or more of them. Since it's auto-picked to 'fast', you'd have to change each one to 'normal.' If it's already set to 'normal,' it's quicker and easier to convert (saves time). :D

**Comment by Arlisbloxer05** [comment]
Exactly, doesn't make much sense to go "Oh, i'll have these go fast and be low quality as heck, and have this one be set to slow"

And speaking of UI, just gonna mention this now but this program doesn't like making chara_4 files for whatever reason (probably because they're 162x162) so you might wanna fix that.
